programs:
  goodnight:
    command: config/goodnight
    at_launch: true
    restart: on_failure
    exit_code: 130
    signal: SIGINT
    replicas: 3
    healthy_uptime: 5

  signal:
    command: config/signal
    at_launch: true
    restart: on_failure
    exit_code: 130
    signal: SIGINT
    replicas: 1
    healthy_uptime: 5
  tests:
    command: /bin/ls
    environment:
      key: BAZ
    at_launch: true
    workdir: /tmp
    stdout: /Users/zekao/Desktop/42 | Projects/Taskmaster/ntm_test.txt
    restart: on_failure
    exit_code: 42

  rap:
    command: config/ratio
    args:
      - "hello"
      - "world"
    environment:
      key: BAZ
    healthy_uptime: 5
    at_launch: true

  hello:
    command: /bin/echo
    args:
      - "hello"
      - "world"
    replicas: 3
    at_launch: false
    restart: on_failure
    exit_code: 42
    healthy_uptime: 5
    retries: 3
    signal: SIGTERM
    exit_timeout: 10
    stdout: /dev/null
    stderr: /dev/null
    environment:
      key: BAZ
    workdir: /app
    umask: 777

  world:
    command: /bin/echo
    replicas: 3
    at_launch: false
    restart: on_failure
    exit_code: 42
    healthy_uptime: 5
    retries: 3
    signal: SIGTERM
    exit_timeout: 10
    stdout: /dev/null
    stderr: /dev/null
    environment:
      key: BAZ
    workdir: /app
    umask: 777
