programs:
  wait:
    command: config/wait_prg
    at_launch: true
    restart: on_failure
    exit_code:
      - 130
    signal: SIGINT
    replicas: 3
    healthy_uptime: 5

  signal:
    command: config/signal_prg
    at_launch: true
    restart: on_failure
    exit_code:
      - 130
    signal: SIGINT
    replicas: 1
    healthy_uptime: 5

  tests:
    command: /bin/ls
    environment:
      key: BAZ
    at_launch: false
    workdir: /tmp
    stdout: /dev/null
    restart: on_failure
    exit_code:
      - 2

  env:
    command: config/env_prg
    environment:
      foo: BAR
    healthy_uptime: 5
    at_launch: false
    stdout: /dev/stdout

  hello:
    command: /bin/echo
    args:
      - "hello"
      - "world"
    replicas: 3
    at_launch: false
    restart: on_failure
    exit_code:
      - 42
    healthy_uptime: 5
    retries: 3
    signal: SIGTERM
    exit_timeout: 10
    stdout: /dev/null
    stderr: /dev/null
    environment:
      key: BAZ
    workdir: /app
    umask: 777

  world:
    command: /bin/echo
    replicas: 3
    at_launch: false
    restart: on_failure
    exit_code:
      - 215
    healthy_uptime: 5
    retries: 3
    signal: SIGTERM
    exit_timeout: 10
    stdout: /dev/null
    stderr: /dev/null
    environment:
      key: BAZ
    workdir: /app
    umask: 777

  umask:
    command: config/umask_prg
    at_launch: false
    umask: 707

  failure:
    command: config/failure_prg
    exit_code:
      - 1
      - 212

  success:
    command: config/failure_prg
    exit_code:
      - 215
      - 12
      - 42
